### ISSUE TITLE
Object(...) is not a function ERROR

### ISSUE THREAD

**Issue by gabr1elt-arc** [marcusolsson/grafana-gantt-panel#89]
This error appears on any datasource I've tried (Azure Monitor, CSV TestData DB).

No graph is displayed.

Running on grafana latest container (on cloud and local).

No idea what the issue refers to. Please help.

**Comment by dmncr** [comment]
Experiencing the same issue with the 9.0.0-beta2 and 9.0.0-beta3 containers (works fine with 9.0.0-beta1).

**Comment by PabblRepos** [comment]
Same with Grafana 9.0.0 release

**Comment by jammiemil** [comment]
Also having this issue in 9.0.1 :(

Console:

`
TypeError: Object(...) is not a function
    at eval (helpers.ts:11:36)
    at eval (GanttChart.tsx:346:17)
    at Array.map (<anonymous>)
    at un (GanttChart.tsx:301:37)
    at ra (react-dom.production.min.js:157:137)
    at Zs (react-dom.production.min.js:267:460)
    at Ou (react-dom.production.min.js:250:347)
    at Eu (react-dom.production.min.js:250:278)
    at ku (react-dom.production.min.js:250:138)
    at vu (react-dom.production.min.js:243:163)
as @ react-dom.production.min.js:216

`

**Comment by marcusolsson** [comment]
Thanks for the heads-up! I'll look into this. Most likely an API change in Grafana 9.0. Hopefully, I won't need to bump the required version.
